Repository qdrant/kubernetes-api, pull requests merged in 2024-10, with the labels that each got.

#25 Add distribution and storage params
  api/v1/qdrantcluster_types.go
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: feature

#26 Update several modules (and move to Go 1.23)
  .github/workflows/pr-workflow.yaml
  go.mod
  go.sum
Labels: dependencies, chore

#28 Added QC.Status.DeleteInProgessNodeIndexes field
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusters.yaml
Labels: bug, fix

#29 Rename `QdrantVersion` to `QdrantRelease`
  Makefile
  api/v1/qdrantrelease_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/templates/management-crds/qdrant.io_qdrantreleases.yaml
  docs/api.md
Labels: fix

#31 Move async scorer into storage performance
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix

#33 Changes to ingress config - Remove unused ingress path type routing - Add traefik additionalRuleNames
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: feature
