Repository qdrant/kubernetes-api, pull requests merged in 2024-11, with the labels that each got.

#37 Add field to hide JWT dashboard
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: feature

#39 Remove AdditionalRuleNames, since they are not needed anymore
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: feature

#38 Add k3s as a detectable Kubernetes distribution
  api/v1/region_types.go
Labels: feature

#40 Added QC.Spec.RestartAllPodsConcurrently for adding one-shot-restart functionality
  api/v1/qdrantcluster_types.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: enhancement

#42 No need to restart all pods if RestartAllPodsConcurrently setting has been changed.
  api/v1/qdrantcluster_types.go
Labels: bug, fix

#41 Add monitoring to region status
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  docs/api.md
Labels: feature

#43 Add snapshot duration field in QdrantClusterSnapshot status
  api/v1/qdrantclustersnapshot_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclustersnapshots.yaml
Labels: feature

#44 Added a small test to check Validate (missing the resources)
  api/v1/qdrantcluster_types_test.go
  go.mod
Labels: chore

#45 Fix flipping `QdrantCluster.Spec.ServicePerNode` from `false` to `true`
  api/v1/qdrantcluster_types.go
Labels: bug, fix

#50 Duplicate CRDs into crds directory to be used in kustomizations
  Makefile
  crds/qdrant.io_qdrantcloudregions.yaml
  crds/qdrant.io_qdrantclusterrestores.yaml
  crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusterscheduledsnapshots.yaml
  crds/qdrant.io_qdrantclustersnapshots.yaml
Labels: feature
