Repository qdrant/kubernetes-api, pull requests merged in 2024-09, with the labels that each got.

#9 Fix typo in pullSecretName
  api/v1/qdrantcluster_types.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix

#10 Make it possible to see diff between false and not-set
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
Labels: bug, fix

#11 Enhance the ClusterManager default
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: enhancement

#14 Update module name
  go.mod
Labels: chore

#13 remove spec.operatorVersion field
  api/v1/qdrantcluster_types.go
  api/v1/qdrantclusterrestore_types.go
  api/v1/qdrantclusterscheduledsnapshot_types.go
  api/v1/qdrantclustersnapshot_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusterrestores.yaml
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusters.yaml
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusterscheduledsnapshots.yaml
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclustersnapshots.yaml
  docs/api.md
Labels: fix

#15 Store individual node indexes (as preparation of allowing 'missing' nodes)
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantcloudregions.yaml
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusters.yaml
Labels: enhancement

#16 Added RecreateNodeAnnotationKey const
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclusters.yaml
Labels: enhancement

#20 Add SnapshotHandle in VolumeSnapshotInfo
  api/v1/qdrantclustersnapshot_types.go
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantclustersnapshots.yaml
  docs/api.md
Labels: feature

#19 Move crds to templates folder
  .github/workflows/pr-workflow.yaml
  Makefile
  charts/qdrant-operator-crds/crds/qdrant.io_qdrantversions.yaml
  charts/qdrant-operator-crds/templates/management-crds/qdrant.io_qdrantversions.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusterrestores.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusters.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclusterscheduledsnapshots.yaml
  charts/qdrant-operator-crds/templates/region-crds/qdrant.io_qdrantclustersnapshots.yaml
  charts/qdrant-operator-crds/values.yaml
Labels: chore
