Repository qdrant/kubernetes-api, pull requests merged in 2025-01, with the labels that each got.

#64 Updated several modules
  go.mod
  go.sum
Labels: dependencies, chore

#65 Added QC.Spec.StartupDelaySeconds
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: enhancement

#70 Add Components field and deprecate HelmReleases and HelmRepositories fields in Region type
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  crds/qdrant.io_qdrantcloudregions.yaml
  docs/api.md
Labels: fix
