Repository qdrant/kubernetes-api, pull requests merged in 2025-04, with the labels that each got.

#110 Fix StoragePerformanceConfig, configurable Traefik entrypoints
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix

#112 Fixed typo
  api/v1/qdrantentity_types.go
Labels: bug, fix

#114 Fix typo in traefik entryPoints json field
  api/v1/qdrantcluster_types.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix

#113 Add note on how kubernetes-api is deployed
  README.md
Labels: chore

#116 Remove GetQdrantClusterCrdForHash helper
  api/v1/qdrantcluster_types.go
  api/v1/qdrantcluster_types_test.go
Labels: chore

#115 Upate HelmRepository to v1 and HelmRelease to v2
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  crds/qdrant.io_qdrantcloudregions.yaml
Labels: fix
