Repository qdrant/kubernetes-api, pull requests merged in 2025-02, with the labels that each got.

#72 Add `MarkedForDeletion` field to `ComponentReference`
  api/v1/region_types.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  crds/qdrant.io_qdrantcloudregions.yaml
  docs/api.md
Labels: feature

#73 Remove operator v1 specific phase and status field
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: chore

#81 Improve hybrid cloud env status
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantcloudregions.yaml
  crds/qdrant.io_qdrantcloudregions.yaml
  docs/api.md
Labels: feature

#84 Add gpu type to cluster spec
  api/v1/qdrantcluster_types.go
  api/v1/qdrantclusterrestore_types.go
  api/v1/qdrantclusterscheduledsnapshot_types.go
  api/v1/qdrantclustersnapshot_types.go
  api/v1/region_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: feature

#86 Make inference config optional and replace token with enabled boolean
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix
