Repository qdrant/kubernetes-api, pull requests merged in 2025-03, with the labels that each got.

#88 Fix: `.Inference.Enabled` is not a pointer
  api/v1/qdrantcluster_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantclusters.yaml
  crds/qdrant.io_qdrantclusters.yaml
  docs/api.md
Labels: fix

#91 Fix security warning that Workflow does not contain permissions
  .github/workflows/pr-workflow.yaml
Labels: fix

#92 Added support for resource QdrantEntity
  api/v1/qdrantentity_types.go
  api/v1/qdrantentity_types_test.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantentities.yaml
  crds/qdrant.io_qdrantentities.yaml
  docs/api.md
Labels: enhancement

#98 Add kubeconform as a Github action step
  .github/workflows/pr-workflow.yaml
Labels: chore

#99 add lastUpdatedAt to Entity Status to track changes
  api/v1/qdrantentity_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantentities.yaml
  crds/qdrant.io_qdrantentities.yaml
Labels: feature

#105 add microsec precision for Entity timestamps
  api/v1/qdrantentity_types.go
  docs/api.md
Labels: feature

#106 switch to observedGeneration to track Entity Status updates
  api/v1/qdrantentity_types.go
  api/v1/zz_generated.deepcopy.go
  charts/qdrant-kubernetes-api/templates/region-crds/qdrant.io_qdrantentities.yaml
  crds/qdrant.io_qdrantentities.yaml
Labels: feature
